spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec_re
    username: postgres
    password: postgres
  messages:
    basename: ValidationMessages
  sql:
    init:
      mode: always
mybatis:
  type-handlers-package: com.example.ec_re.typehandler
